Inconsistent conf names deploy.waitIterations + deploy_waitIterations
folio-org/okapi pull request #1099
Opened 2021-03-03 15:57 UTC by julianladisch

As requested by Adam on #1095.

2021-03-03 16:10 UTC, adamdickmeiss requested changes
You changed behavior. The property `deploy.waitIterations` will no longer work.

2021-03-04 07:00 UTC, adamdickmeiss approved these changes
Looks good. I misread the PR yesterday, not realizing this based on your earlier PR, not based on master. Sorry.

2021-03-04 20:30 UTC, hjiebsco approved these changes

2021-03-08 16:36 UTC, julianladisch commented
I disagree with this pull request.
All Okapi conf variables use the underscore syntax that cannot been used in okapi.sh/okapi.conf.
This pull introduces the dot syntax for deploy_waitIterations resulting in inconsistent names.
I merge this because I am a minority.

2021-03-08 16:36 UTC, merged